### ISSUE TITLE
add option to start with SvelteKit instead of Svelte

### ISSUE THREAD

**Issue by vfxturjo** [alex8088/quick-start#40]
### Clear and concise description of the problem

self explanatory

### Used Scaffolding

create-electron

### Suggested solution

Please add an option to add SvelteKit and SvelteKit typescript to a new project

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/quick-start/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/quick-start/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://github.com/alex8088/quick-start#readme).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/quick-start/issues) that reports the same bug to avoid creating a duplicate.

**Comment by Roboroads** [comment]
I have a template which got it working on dev, but compiling it to an executable gives me an error that it needs an index.html.

```
The following Vite config options will be overridden by SvelteKit:
  - root
The following Vite config options will be overridden by SvelteKit:
  - build.outDir
  - build.rollupOptions.input
The electron vite renderer config build.target is not "chrome?" or "es?". This could be a mistake.
vite v5.3.4 building SSR bundle for production...
✓ 79 modules transformed.
vite v5.3.4 building for production...
✓ 0 modules transformed.
x Build failed in 3ms
x Build failed in 738ms
error during build:
[vite-plugin-sveltekit-compile] Could not resolve entry module "index.html".
Could not resolve entry module "index.html".
    at getRollupError (file:///home/roboroads/BagOfHolding/I.T.it/Projects/electron-vite-sveltekit/node_modules/rollup/dist/es/shared/parseAst.js:392:41)
    at error (file:///home/roboroads/BagOfHolding/I.T.it/Projects/electron-vite-sveltekit/node_modules/rollup/dist/es/shared/parseAst.js:388:42)
    at ModuleLoader.loadEntryModule (file:///home/roboroads/BagOfHolding/I.T.it/Projects/electron-vite-sveltekit/node_modules/rollup/dist/es/shared/node-entry.js:19157:20)
    at async Promise.all (index 0)

```

**Comment by IgorRain** [comment]
I also tried to use this template with svelte-kit. It's possible, but I'm not happy with the solution I got albeit I haven't tried to perfect it (it's good enough for my purpose). The main problem is that both electron-vite and sveltekit treats vite interaction as they are the only one. I'm not a vite/electron/nodejs/sveltekit expert, so take my solution with a grain of salt and security concerns:
1) create a monorepo;
2) create an `desktop` app via `@quick-start/electron`;
3) remove renderer from `desktop`;
4) create `ui` app via `sv create` with static-adapter;
5) for `ui` set `bundleStrategy` to `single` (file `svelte.config.js`);
6) in `ui` vite config set port for server and hmr and `strictPort: true` for server;
7) in `desktop` vite config for renderer set server proxy to server configured in `ui`, hmr client port to the same port as `ui`'s hmr, root to `ui` build directory, rollup input to index.html in `ui` build directory;
8) add `electron-serve` as dependency to `desktop`;
9) extend `desktop`'s main accoding to `electron-serve` usage;
10) build `ui` then `desktop`.

Feel free to correct me.
